//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Turns.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUtils {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUtils() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carvajal.Turns.Utils.Resources.ResourceUtils", typeof(ResourceUtils).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;!-- &lt;body&gt; --&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///	&lt;div style=&quot;padding-top:50px&quot;&gt;
        ///	&lt;/div&gt;
        ///	&lt;div  style=&quot;padding-top:50px !important&quot;&gt;
        ///		&lt;div class=&quot;col-md-12&quot;&gt;
        ///		
        ///		
        ///		&lt;b&gt;Apreciado &lt;%UserName%&gt;&lt;/b&gt;
        ///		&lt;br&gt;		
        ///		&lt;br&gt;
        ///		
        ///		&lt;p style=&quot;text-align:justify&quot;&gt;		
        ///			Esta comunicación es para notificarle que se ha realizado cambios en la información de su correo electrónico, lo cual ocasiono un cambio en la contraseña para el ingreso al Servicio de Agendamiento de Tu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;!-- &lt;body&gt; --&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///	&lt;div style=&quot;padding-top:50px&quot;&gt;
        ///	&lt;/div&gt;
        ///	&lt;div  style=&quot;padding-top:50px !important&quot;&gt;
        ///		&lt;div class=&quot;col-md-12&quot;&gt;
        ///		
        ///		
        ///		&lt;b&gt;Apreciado &lt;%UserName%&gt;&lt;/b&gt;
        ///		&lt;br&gt;		
        ///		&lt;br&gt;
        ///		
        ///		&lt;p style=&quot;text-align:justify&quot;&gt;		
        ///			Esta comunicación es para notificarle que se ha realizado la creación de su usuario para el ingreso al Servicio de Agendamiento de Turnos.
        /// &lt;/p&gt;
        /// &lt;p&gt;
        ///   País: &lt;%Country%&gt;&lt;br&gt;
        ///   Comercio: &lt;%Comerce%&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewUserEmail {
            get {
                return ResourceManager.GetString("NewUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css&quot; integrity=&quot;sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css&quot; integrity=&quot;sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///&lt;script src=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css&quot; integrity=&quot;sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css&quot; integrity=&quot;sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///&lt;script src=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SendUserPassword {
            get {
                return ResourceManager.GetString("SendUserPassword", resourceCulture);
            }
        }
    }
}
