//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Turns.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carvajal.Turns.Utils.Resources.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango de Fechas no Válido.
        /// </summary>
        internal static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe información para visualizar.
        /// </summary>
        internal static string M10 {
            get {
                return ResourceManager.GetString("M10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso no se terminó satisfactoriamente. Intente nuevamente en unos segundos..
        /// </summary>
        internal static string M12 {
            get {
                return ResourceManager.GetString("M12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;¿Está seguro de salir? Se perderán los cambios que no ha guardado&quot;.
        /// </summary>
        internal static string M17 {
            get {
                return ResourceManager.GetString("M17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados son inválidos o el usuario se encuentra inactivo.
        /// </summary>
        internal static string M27 {
            get {
                return ResourceManager.GetString("M27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no coincide con los requerimientos solicitados.
        /// </summary>
        internal static string M28 {
            get {
                return ResourceManager.GetString("M28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña y su confirmación no coinciden..
        /// </summary>
        internal static string M29 {
            get {
                return ResourceManager.GetString("M29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña fue restablecida con éxito. Por favor ingresa las nuevas credenciales para iniciar sesión.
        /// </summary>
        internal static string M30 {
            get {
                return ResourceManager.GetString("M30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se enviará el código para restablecer contraseña el correo electrónico ingresado.
        /// </summary>
        internal static string M33 {
            get {
                return ResourceManager.GetString("M33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Nueva contraseña no puede ser igual a las cinco ultimas contraseñas registradas en el sistema.
        /// </summary>
        internal static string M34 {
            get {
                return ResourceManager.GetString("M34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la modificación del usuario de forma correcta.
        /// </summary>
        internal static string M36 {
            get {
                return ResourceManager.GetString("M36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar la modificación al usuario seleccionado.
        /// </summary>
        internal static string M37 {
            get {
                return ResourceManager.GetString("M37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico ingresado ya se encuentra registrado para otro usuario.
        /// </summary>
        internal static string M38 {
            get {
                return ResourceManager.GetString("M38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar {0}.
        /// </summary>
        internal static string M5 {
            get {
                return ResourceManager.GetString("M5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso no se terminó satisfactoriamente.
        /// </summary>
        internal static string M65 {
            get {
                return ResourceManager.GetString("M65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar la activación del usuario ya se encuentra registrado.
        /// </summary>
        internal static string M66 {
            get {
                return ResourceManager.GetString("M66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y/o Contraseña no válidos.
        /// </summary>
        internal static string M7 {
            get {
                return ResourceManager.GetString("M7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha modificar se encuentra asociado ha otro comercio por favor valide la informacion suministrada.
        /// </summary>
        internal static string M99 {
            get {
                return ResourceManager.GetString("M99", resourceCulture);
            }
        }
    }
}
