//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Carvajal.Turns.Utils.Data
{


    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.springframework.net/nms/common/2008-08-05")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.springframework.net/nms/common/2008-08-05", IsNullable = false)]
    public partial class MessageFileMassive
    {
        public decimal IdLoad { get; set; }
        public decimal IdCompany { get; set; }
        public string FileNameTmp { get; set; }
        public string Country { get; set; }
        public string FileName { get; set; }
        public string TypeLoad { get; set; }
        public decimal IdUser { get; set; }
    }
}
