//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Carvajal.Turns.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Xml.Serialization;


// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
public partial class PurchaseOrder
{

    private decimal idUser;

    private string timeStamp;

    private string country;

    private string idMerchantField;

    private string idPointOfSaleField;

    private string idManufacturerField;

    private string sendReferenceField;

    private string dateDeliveryField;

    private List<PurchaseOrderDetail> purchaseOrderDetails;

    /// <comentarios/>
    public string IdMerchant
    {
        get
        {
            return this.idMerchantField;
        }
        set
        {
            this.idMerchantField = value;
        }
    }

    /// <comentarios/>
    public string IdPointOfSale
    {
        get
        {
            return this.idPointOfSaleField;
        }
        set
        {
            this.idPointOfSaleField = value;
        }
    }

    /// <comentarios/>
    public string IdManufacturer
    {
        get
        {
            return this.idManufacturerField;
        }
        set
        {
            this.idManufacturerField = value;
        }
    }

    /// <comentarios/>
    public string SendReference
    {
        get
        {
            return this.sendReferenceField;
        }
        set
        {
            this.sendReferenceField = value;
        }
    }

    /// <comentarios/>
    public string DateDelivery
    {
        get
        {
            return this.dateDeliveryField;
        }
        set
        {
            this.dateDeliveryField = value;
        }
    }

    public List<PurchaseOrderDetail> PurchaseOrderDetails
    {
        get
        {
            return this.purchaseOrderDetails;
        }
        set
        {
            this.purchaseOrderDetails = value;
        }
    }

    public string Country
    {
        get
        {
            return country;
        }
        set
        {
            country = value;
        }
    }

    public string TimeStamp
    {
        get { return this.timeStamp; }
        set { this.timeStamp = value; }
    }

    public decimal IdUser
    {
        get { return idUser; }
        set { idUser = value; }
    }
}
